export const AUTH_ROUTE = '/auth'
export const PROFILE_ROUTE = '/profile'
export const HOME_ROTE = '/'
export const REGISTRATION_ROUTE = '/registration'
export const PROFILE_SETTINGS_ROUTE = '/profile/settings'
export const ADMIN_ROUTE = '/admin'
export const GARANT_ROUTE = '/garant'